//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessirveWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessirveWSEntities : DbContext
    {
        public MessirveWSEntities()
            : base("name=MessirveWSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<SubCategoria> SubCategorias { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<CuponDescuento> CuponDescuentoes { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<OrdenProducto> OrdenProductoes { get; set; }
        public virtual DbSet<ProductoEmpresa> ProductoEmpresas { get; set; }
    }
}
