//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessirveWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.OrdenProductoes = new HashSet<OrdenProducto>();
        }
    
        public int IdOrden { get; set; }
        public int NumeroOrden { get; set; }
        public string Estado { get; set; }
        public decimal Impuesto { get; set; }
        public bool Envio { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalOrden { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public int IdCupon { get; set; }
        public int IdUsuarioNormal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual CuponDescuento CuponDescuento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenProducto> OrdenProductoes { get; set; }
    }
}
